layout_spectrum: 0.7191193
typography_spectrum: 0.3968851
color:
  saturation: 0.3727477
  lightness: 0.0673611
  brandStrength: 1
  brandColors:
    - '#F1E1BF'
    - '#636768'
    - '#DBB682'
    - '#D46339'
    - '#77BEB6'
  rhythmicContrast: 0.5319048
name: Digital-Talent
