collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.3968851
color:
  saturation: 0.3727477
  brandStrength: 1
  rhythmicContrast: 0.5319048
  brandColors:
    - '#F1E1BF'
    - '#636768'
    - '#DBB682'
    - '#D46339'
    - '#77BEB6'
  lightness: 0.0673611
layout_spectrum: 0
name: Digital-Talent
